export const ADD_TO_CART_START = 'ADD_TO_CART_START';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';

export const LOAD_CART_START = 'LOAD_CART_START';
export const LOAD_CART_SUCCESS = 'LOAD_CART_SUCCESS';
export const LOAD_CART_FAIL = 'LOAD_CART_FAIL';


export const REMOVE_FROM_CART_START = 'REMOVE_FROM_CART_START';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_FAIL = 'REMOVE_FROM_CART_FAIL';

export const BUY_FROM_CART_START = 'BUY_FROM_CART_START';
export const BUY_FROM_CART_SUCCESS = 'BUY_FROM_CART_SUCCESS';
export const BUY_FROM_CART_FAIL = 'BUY_FROM_CART_FAIL';