export const LOAD_VENDOR_PROFILES_START = 'LOAD_VENDOR_PROFILES_START';
export const LOAD_VENDOR_PROFILES_SUCCESS = 'LOAD_VENDOR_PROFILES_SUCCESS';
export const LOAD_VENDOR_PROFILES_FAIL = 'LOAD_VENDOR_PROFILES_FAIL';

